const SET_SCHEDULER_WIDTH = 'SET_SCHEDULER_WIDTH';
const SET_VISIBLE_START_DATE = 'SET_VISIBLE_START_DATE';
const SET_VISIBLE_END_DATE = 'SET_VISIBLE_END_DATE';

export default {
    SET_SCHEDULER_WIDTH,
    SET_VISIBLE_START_DATE,
    SET_VISIBLE_END_DATE
};
